version: "3"

services:
  metric-counter:
    image: metric-counter
    build:
      context: .
      dockerfile: counter/Dockerfile
    env_file: .env
    depends_on:
      - mongo1
      - mongo2
      - mongo3
    restart: always

  ingester:
    image: ingester
    build:
      context: .
      dockerfile: ingester/Dockerfile
    deploy:
      replicas: 3
    env_file: .env
    depends_on:
      - mongo1
      - mongo2
      - mongo3

  app:
    image: app
    build:
      context: .
      dockerfile: app/Dockerfile
    deploy:
      replicas: 1
    env_file: .env
    depends_on:
      - mongo1
      - mongo2
      - mongo3
    restart: always
    ports:
      - 3000:8080

  mongo1:
    hostname: mongo1
    container_name: localmongo1
    image: mongo:4.2
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - 27017:27017
    entrypoint: [ "/usr/bin/mongod", "--bind_ip_all", "--replSet", "rs0" ]
    volumes:
      - /Users/ms/Documents/src/gitlab/taxi-ingester/data:/data/db

  mongo2:
    hostname: mongo2
    container_name: localmongo2
    image: mongo:4.2
    expose:
      - 27017
    ports:
      - 27018:27017
    restart: always
    entrypoint: [ "/usr/bin/mongod", "--bind_ip_all", "--replSet", "rs0" ]

  mongo3:
    hostname: mongo3
    container_name: localmongo3
    image: mongo:4.2
    expose:
      - 27017
    ports:
      - 27019:27017
    restart: always
    entrypoint: [ "/usr/bin/mongod", "--bind_ip_all", "--replSet", "rs0" ]

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_SERVER: mongo1,mongo2,mongo3
