apiVersion: v1
kind: Service
metadata:
  name: {{ include "taxi-counter.fullname" . }}
  labels:
{{ include "taxi-counter.labels" . | indent 4 }}
spec:
  type: {{ .Values.service.type }}
  spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
  selector:
    app.kubernetes.io/name: {{ include "taxi-counter.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
