replicaCount: 3

image:
  repository: asia.gcr.io/gojek-assignment-251304/taxi-app
  tag: 2
  pullPolicy: IfNotPresent

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

service:
  type: LoadBalancer
  port: 80
  targetPort: 8080

ingress:
  enabled: false
  annotations: {}
  hosts:
    - host: chart-example.local
      paths: []

resources:
  limits:
    cpu: 250m
    memory: 256Mi
  requests:
    cpu: 250m
    memory: 256Mi

nodeSelector: {}

tolerations: []

affinity: {}
